"""empty message

Revision ID: 66436e6df0f4
Revises: 94c2b4e0c125
Create Date: 2017-06-16 15:45:10.281116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66436e6df0f4'
down_revision = '94c2b4e0c125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entry', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_column('entry', 'author_id')
    # ### end Alembic commands ###
